# -*- coding: utf-8 -*-
"""Histogram_Equalization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171SuV6gs9pQ5mGjf9O7QC17-mjI3U-i1
"""

# Importing OpenCV
import cv2

# Importing numpy
import numpy as np

# Importing matplotlib.pyplot
import matplotlib.pyplot as plt

# Reading the image
img = cv2.imread("/content/Flowers.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_1 = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Setting the grid size
plt.figure(figsize=(20,20))

# Plotting the original image
plt.subplot(221)
plt.title('Original')
plt.imshow(img)

# Plotting the histogram for the image
img_hist = cv2.calcHist([img_1],[0],None,[256],[0,256])
plt.subplot(222)
plt.title('Histogram 1')
plt.plot(img_hist)

# Plotting the histogram using the ravel function
plt.subplot(223)
plt.hist(img_1.ravel(), 256, [0,256])
plt.title('Histogram 2')

# Plotting the histogram for colors in the image
for i, col in enumerate(['r', 'g', 'b']):
    hist = cv2.calcHist([img], [i], None, [256], [0, 256])
    plt.subplot(224)
    plt.title('Color Histogram')
    plt.plot(hist, color = col)
    plt.xlim([0, 256])