# -*- coding: utf-8 -*-
"""OpenCV_Task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vwYTnTDKNGuQ4WE03Ys38ZyouIoAaleQ
"""

import numpy as np
import cv2
#Reading an image
img=cv2.imread("/content/bright_image_OpenCV.jpeg")

#Displaying image
from google.colab.patches import cv2_imshow
cv2_imshow(img)

#saving image
from google.colab import files
cv2.imwrite('/content/cat_wallpaper1.png',img)

#resizing image
scale_percent = 40
width = int(img.shape[1] * scale_percent / 100)
height = int(img.shape[0] * scale_percent / 100)

dim = (width, height)

resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
cv2_imshow(resized)

#saving resized image
cv2.imwrite("/content/resized_image.png", resized)

#enhancing image
lab= cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
l_channel, a, b = cv2.split(lab)

clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
cl = clahe.apply(l_channel)

limg = cv2.merge((cl,a,b))

enhanced_img = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)

result = np.hstack((img, enhanced_img))
cv2_imshow(result)

#rotating the image by 270 degrees
rotated_img = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)
cv2_imshow(rotated_img)

#flipping the image horizontally
flipped_img = cv2.flip(img, 1)
cv2_imshow(flipped_img)

#Sharpening an image
kernel = np.array([[0,-1,0],
                   [-1,5,-1],
                   [0,-1,0]])
sharpened = cv2.filter2D(img,-1,kernel)

result = np.hstack((img, sharpened))
cv2_imshow(result)

#grayscale image
grayscale_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(grayscale_img)

#Changing the color format
image_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2_imshow(image_rgb)

#Cropping the image
print("Shape of the image", img.shape)
crop = img[50:180, 100:300]

cv2_imshow(img)
cv2_imshow(crop)

import os
import random

image_dir = '/content/images'

image_files = [os.path.join(image_dir, filename) for filename in os.listdir(image_dir)
if filename.endswith('.jpg') or filename.endswith('.png')]

random_image_path = random.choice(image_files)

random_image = cv2.imread(random_image_path)
cv2_imshow(random_image)